---
- name: This playboook is to install and start httpd package
  hosts: all
  become: true
  tasks:

  - name: install httpd package
    yum: 
      name: httpd
      state: installed

  - name: starting service      
    service:
      name: httpd
      state: started
