---
- name: This playbook is to install httpd package
  hosts: all
  become: true
  tasks:

  - name: installing httpd
    yum:
      name: httpd
      state: installed
    notify: starting service

  handlers:
  - name: starting service
    service:
      name: httpd
      state: started  

     
