---
- name: multiple packages installing by using ansible play book
  hosts: all
  become: true 
  tasks:

  - name: installing multiple packages
    yum:
      name: ['git','tree','which', 'wget','docker']
      state: latest
