---
- name: Remove a service using Ansible
  hosts: all
  become: yes  # To execute commands with elevated privileges (usually as root)
  tasks:
    - name: Stop and disable the service
      systemd:
        name: httpd
        enabled: no
        state: stopped

    - name: Reload systemd manager configuration
      command: systemctl daemon-reload
      become: yes

