---
- name: This playbook is to install httpd package
  hosts: all
  become: true
  tasks:

  - name: installing httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: starting service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: installing apache2
    apt:
      name: apache2
      state: installed
    when: ansible_os_family == "Debian"

  - name: starting service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: coping index file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: '0666'
